import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat_Alternates, Karla } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat_Alternates({ weight: ['900', '700', '400'] })
const karla = Karla({weight:['800','700','600','400']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${karla.className}`}>
        {children}
      </body>
    </html>
  );
}
